---
kind: pipeline
name: lint
platform:
  os: linux
  arch: amd64
steps:
  - name: commit-message
    image: outillage/commitsar
    commands:
      - commitsar -d /drone/src -v
  - name: code
    image: maiwj/drone-dapper:v0.4.2
    privileged: true
    environment:
      BY: dapper
      DIRTY_CHECK: true
    commands:
      - make autok3s lint
      - make autok3s build only
    volumes:
      - name: docker
        path: /var/run/docker.sock
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
trigger:
  event:
    include:
      - push
      - pull_request
node:
  instance: agent-amd64
---
kind: pipeline
name: package-arm64
platform:
  os: linux
  arch: arm64
steps:
  - name: build-arm64
    image: maiwj/drone-dapper:v0.4.2
    environment:
      BY: dapper
      ARCH: arm64
      TAG: "${DRONE_TAG}"
      DAPPER_FILE: Dockerfile-package.dapper
    commands:
      - make autok3s build
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - tag
  - name: compress-arm64
    image: maiwj/drone-dapper:v0.4.2
    privileged: true
    environment:
      BY: dapper
    commands:
      - wget https://github.com/upx/upx/releases/download/v3.96/upx-3.96-arm64_linux.tar.xz
      - tar -xvf upx-3.96-arm64_linux.tar.xz
      - cp upx-3.96-arm64_linux/upx /usr/bin/
      - upx dist/autok3s_*
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - tag
    depends_on:
      - build-arm64
  - name: docker-publish-arm64
    image: plugins/docker
    settings:
      build_args:
        - ARCH=arm64
        - "VERSION=${DRONE_TAG}-linux-arm64"
      custom_dns: 1.1.1.1
      dockerfile: Dockerfile
      repo: cnrancher/autok3s
      tag: "${DRONE_TAG}-linux-arm64"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - tag
    depends_on:
      - compress-arm64
  - name: docker-publish-latest-arm64
    image: plugins/docker
    settings:
      build_args:
        - ARCH=arm64
        - "VERSION=latest-linux-arm64"
      custom_dns: 1.1.1.1
      dockerfile: Dockerfile
      repo: cnrancher/autok3s
      tag: "latest-linux-arm64"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - tag
      ref:
        exclude:
          - "refs/tags/*rc*"
    depends_on:
      - compress-arm64
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
trigger:
  event:
    include:
      - tag
node:
  instance: agent-arm64
depends_on:
  - lint
---
kind: pipeline
name: package-amd64
platform:
  os: linux
  arch: amd64
steps:
  - name: build-amd64
    image: maiwj/drone-dapper:v0.4.2
    environment:
      BY: dapper
      ARCH: amd64
      TAG: "${DRONE_TAG}"
      DAPPER_FILE: Dockerfile-package.dapper
    commands:
      - make autok3s build
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - tag
  - name: compress-amd64
    image: maiwj/drone-dapper:v0.4.2
    privileged: true
    environment:
      BY: dapper
    commands:
      - wget https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz
      - tar -xvf upx-3.96-amd64_linux.tar.xz
      - cp upx-3.96-amd64_linux/upx /usr/bin/
      - upx dist/autok3s_*
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - tag
    depends_on:
      - build-amd64
  - name: docker-publish-amd64
    image: plugins/docker
    settings:
      build_args:
        - ARCH=amd64
        - "VERSION=${DRONE_TAG}-linux-amd64"
      custom_dns: 1.1.1.1
      dockerfile: Dockerfile
      repo: cnrancher/autok3s
      tag: "${DRONE_TAG}-linux-amd64"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - tag
    depends_on:
      - compress-amd64
  - name: docker-publish-latest-amd64
    image: plugins/docker
    settings:
      build_args:
        - ARCH=amd64
        - "VERSION=latest-linux-amd64"
      custom_dns: 1.1.1.1
      dockerfile: Dockerfile
      repo: cnrancher/autok3s
      tag: "latest-linux-amd64"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - tag
      ref:
        exclude:
          - "refs/tags/*rc*"
    depends_on:
      - compress-amd64
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
trigger:
  event:
    include:
      - tag
node:
  instance: agent-amd64
depends_on:
  - lint
---
kind: pipeline
name: cross-build
platform:
  os: linux
  arch: amd64
steps:
  - name: build-cross
    image: maiwj/drone-dapper:v0.4.2
    privileged: true
    environment:
      BY: dapper
      CROSS: true
    commands:
      - make autok3s cross_build
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - tag
  - name: compress
    image: maiwj/drone-dapper:v0.4.2
    privileged: true
    environment:
      BY: dapper
    commands:
      - wget https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz
      - tar -xvf upx-3.96-amd64_linux.tar.xz
      - cp upx-3.96-amd64_linux/upx /usr/bin/
      - upx dist/autok3s_*
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - tag
    depends_on:
      - build-cross
  - name: github_binary_release
    image: ibuildthecloud/github-release:v0.0.1
    settings:
      api_key:
        from_secret: github_token
      prerelease: true
      checksum:
        - sha256
      checksum_file: CHECKSUMsum.txt
      checksum_flatten: true
      files:
        - "dist/autok3s_*"
    when:
      event:
        - tag
    depends_on:
      - compress
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
trigger:
  event:
    include:
      - tag
node:
  instance: agent-amd64
depends_on:
  - lint
---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
  - name: push-manifest
    image: maiwj/drone-dapper:v0.4.2
    environment:
      BY: dapper
      CROSS: true
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
      REPO: cnrancher
      TAG: "${DRONE_TAG}"
      WITHOUT_MANIFEST: false
    commands:
      - make autok3s deploy only
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - tag
  - name: push-manifest-latest
    image: maiwj/drone-dapper:v0.4.2
    environment:
      BY: dapper
      CROSS: true
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
      REPO: cnrancher
      TAG: latest
      WITHOUT_MANIFEST: false
    commands:
      - make autok3s deploy only
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - tag
      ref:
        exclude:
          - "refs/tags/*rc*"
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

trigger:
  event:
    include:
      - tag

node:
  instance: agent-amd64

depends_on:
  - package-amd64
  - package-arm64
---
kind: pipeline
name: publish-release
platform:
  os: linux
  arch: amd64
steps:
  - name: release-note
    image: maiwj/drone-releaser:v0.1.0
    commands:
      - /changelog.sh
    volumes:
      - name: release-note
        path: /release-note
  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      prerelease: true
      overwrite: true
      note: /release-note/CHANGELOG.md
    volumes:
      - name: release-note
        path: /release-note
    when:
      event:
        exclude:
          - push
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
  - name: release-note
    temp: {}
trigger:
  ref:
    include:
      - "refs/heads/master"
      - "refs/heads/release/v*"
      - "refs/tags/v*"
  event:
    include:
      - tag
node:
  instance: agent-amd64
depends_on:
  - cross-build
