---
kind: pipeline
type: docker
name: lint
platform:
  os: linux
  arch: amd64
steps:
  - name: commit-message
    image: aevea/commitsar:0.18.0
    commands:
      - commitsar -d /drone/src -v
  - name: code
    image: rancher/dapper:v0.5.8
    privileged: true
    environment:
      DIRTY_CHECK: "true"
    commands:
      - dapper build
    volumes:
      - name: docker
        path: /var/run/docker.sock
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
trigger:
  event:
    include:
      - push
      - pull_request
node:
  instance: agent-amd64

---
kind: pipeline
type: docker
name: package
platform:
  os: linux
  arch: amd64
steps:
  - name: code
    image: rancher/dapper:v0.5.8
    environment:
      TAG: "${DRONE_TAG}"
    commands:
      - dapper cross_build
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: install-buildx-support
    image: tonistiigi/binfmt
    privileged: true
    entrypoint:
      - /usr/bin/binfmt
    command:
      - --install
      - all
    when:
      event:
        - tag

  - name: docker-publish-arm64
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      platforms: linux/amd64,linux/arm64/v8
      dockerfile: Dockerfile
      repo: cnrancher/autok3s
      tags:
        - ${DRONE_TAG}
        - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - tag

  - name: docker-publish-latest-arm64
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      platforms: linux/amd64,linux/arm64/v8
      build_args:
        - "VERSION=latest"
      dockerfile: Dockerfile
      repo: cnrancher/autok3s
      tag: "latest"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - tag
      ref:
        exclude:
          - "refs/tags/*rc*"

  - name: github_binary_release
    image: ibuildthecloud/github-release:v0.0.1
    settings:
      api_key:
        from_secret: github_token
      prerelease: true
      checksum:
        - sha256
      checksum_file: CHECKSUMsum.txt
      checksum_flatten: true
      files:
        - "dist/autok3s_*"
    when:
      event:
        - tag

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
trigger:
  event:
    include:
      - tag
node:
  instance: agent-amd64
depends_on:
  - "lint"

---
kind: pipeline
type: docker
name: publish-release
platform:
  os: linux
  arch: amd64
steps:
  - name: release-note
    image: maiwj/drone-releaser:v0.1.0
    commands:
      - /changelog.sh
    volumes:
      - name: release-note
        path: /release-note
  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      prerelease: true
      overwrite: true
      note: /release-note/CHANGELOG.md
    volumes:
      - name: release-note
        path: /release-note
    when:
      event:
        exclude:
          - push
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
  - name: release-note
    temp: {}
trigger:
  ref:
    include:
      - "refs/heads/master"
      - "refs/heads/release/v*"
      - "refs/tags/v*"
  event:
    include:
      - tag
node:
  instance: agent-amd64
depends_on:
  - package
