---
kind: pipeline
name: lint
platform:
  os: linux
  arch: amd64
steps:
  - name: commit-message
    image: outillage/commitsar
    commands:
      - commitsar -d /drone/src -v
  - name: code
    image: maiwj/drone-dapper:v0.4.2
    privileged: true
    environment:
      BY: dapper
      DIRTY_CHECK: true
    commands:
      - make autok3s lint
    volumes:
      - name: docker
        path: /var/run/docker.sock
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
trigger:
  event:
    include:
      - push
      - pull_request
node:
  instance: agent-amd64
---
kind: pipeline
name: integration-test
platform:
  os: linux
  arch: amd64
steps:
  - name: build
    image: maiwj/drone-dapper:v0.4.2
    privileged: true
    environment:
      BY: dapper
      CROSS: false
    commands:
      - make autok3s build only
    volumes:
      - name: docker
        path: /var/run/docker.sock
  - name: verify
    image: maiwj/drone-dapper:v0.4.2
    privileged: true
    environment:
      BY: dapper
    commands:
      - make autok3s unit only
    volumes:
      - name: docker
        path: /var/run/docker.sock
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
trigger:
  event:
    include:
      - push
      - pull_request
node:
  instance: agent-amd64
depends_on:
  - lint
---
kind: pipeline
name: cross-build
platform:
  os: linux
  arch: amd64
steps:
  - name: build
    image: maiwj/drone-dapper:v0.4.2
    privileged: true
    environment:
      BY: dapper
      CROSS: true
    commands:
      - make autok3s build
    volumes:
      - name: docker
        path: /var/run/docker.sock
  - name: compress
    image: maiwj/drone-dapper:v0.4.2
    privileged: true
    environment:
      BY: dapper
    commands:
      - wget https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz
      - tar -xvf upx-3.96-amd64_linux.tar.xz
      - cp upx-3.96-amd64_linux/upx /usr/bin/
      - upx -9 dist/autok3s_*
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - tag
    depends_on:
      - build
  - name: github_binary_release
    image: ibuildthecloud/github-release:v0.0.1
    settings:
      api_key:
        from_secret: github_token
      prerelease: true
      checksum:
        - sha256
      checksum_file: CHECKSUMsum.txt
      checksum_flatten: true
      files:
        - "dist/autok3s_*"
    when:
      event:
        - tag
    depends_on:
      - compress
  - name: package
    image: maiwj/drone-dapper:v0.4.2
    environment:
      BY: dapper
      CROSS: true
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
      REPO: cnrancher
      WITHOUT_MANIFEST: false
    commands:
      - make autok3s package only
      - make autok3s deploy only
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - tag
    depends_on:
      - compress
  - name: package-latest
    image: maiwj/drone-dapper:v0.4.2
    environment:
      BY: dapper
      CROSS: true
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
      REPO: cnrancher
      TAG: latest
      WITHOUT_MANIFEST: false
    commands:
      - make autok3s package only
      - make autok3s deploy only
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - tag
      ref:
        exclude:
          - "refs/tags/*rc*"
    depends_on:
      - compress
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
trigger:
  event:
    include:
      - tag
node:
  instance: agent-amd64
depends_on:
  - integration-test
---
kind: pipeline
name: manifest
platform:
  os: linux
  arch: amd64
steps:
  - name: release-note
    image: maiwj/drone-releaser:v0.1.0
    commands:
      - /changelog.sh
    volumes:
      - name: release-note
        path: /release-note
  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      prerelease: true
      overwrite: true
      note: /release-note/CHANGELOG.md
    volumes:
      - name: release-note
        path: /release-note
    when:
      event:
        exclude:
          - push
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
  - name: release-note
    temp: {}
trigger:
  ref:
    include:
      - "refs/heads/master"
      - "refs/heads/release/v*"
      - "refs/tags/v*"
  event:
    include:
      - tag
node:
  instance: agent-amd64
depends_on:
  - cross-build

