name: pull request
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  pr-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Commitsar check
        uses: aevea/commitsar@v0.20.2
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0
      - name: Build to test
        run: |
          make autok3s build only
          bin/$(go env GOOS)/$(go env GOARCH)/autok3s version
