name: Testing

on:
  - pull_request

jobs:
  Test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - name: Build Image
        run: |
          git tag v0.0.1
          make autok3s
          docker build . -t cnrancher/autok3s:latest
      - name: Run e2e
        run: |
          sudo curl -L https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          sudo chmod u+x /usr/local/bin/docker-compose
          cd test/e2e && ./start.sh
